name: Matricula
on:
  push:
    branches:
      - main # or specify your branch

jobs:
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show databases
      run: mysql -h ${{ secrets.DB_HOSTNAME }} -P 3306 -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES";
    - name: Run a sample SQL on remote
      run: mysql -h ${{ secrets.DB_HOSTNAME }} -P 3306 -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source D:/OneDrive/Área de Trabalho/FIEB/guitess/Matricula.sql";
