name: Matricula

on:
  push:
    branches:
      - main # ou especifique o nome do seu branch

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Test Output
        run: echo "Here is a test"
    
  connect-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show databases
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root -p32243100 -e "SHOW DATABASES";
